[versions]
#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
# Mappings
parchment = "2024.07.07"
parchmentMinecraft = "1.21"
# Plugins
modDevGradle = "2.0.78"
# Dependencies
minecraft = "1.21.1"
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
neforge = "21.1.219"
emi = "1.1.10+1.21"
jei = "19.25.0.322"
top = "1.21_neo-12.0.4-6"
patchouli = "1.21.1-92-NEOFORGE"
lombok = "1.18.36"
# IMPORTANT change both this and the tfc file id for things to update correclty
tfc = "4.0.19-beta"
tfcFileId = "7634816"
fusionctm = "1.21.11"
fusionctmFileId = "6916658"
# Non standard version
jadeFileId = "5591256"
modernfixFileId = "6766126"
# Test libs
junit-jupiter = "5.10.3"
junit-platform-launcher = "1.10.3"



[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
emi = { group = "dev.emi", name = "emi-neoforge", version.ref = "emi" }
top = { group = "mcjty.theoneprobe", name = "theoneprobe", version.ref = "top" }
patchouli = { group = "vazkii.patchouli", name = "Patchouli", version.ref = "patchouli" }
# Non standard maven
jade = { group = "curse.maven", name = "jade-324717", version.ref = "jadeFileId" }
modernfix = { group = "curse.maven", name = "modernfix-790626", version.ref = "modernfixFileId" }
tfc = { group = "curse.maven", name = "TerraFirmaCraft-302973", version.ref = "tfcFileId" }
fusionctm = { group = "maven.modrinth", name = "FusionConnectedTextures-854949", version.ref = "fusionctmFileId" }

# Test libs
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }

[bundles]
jei-api = ["jei-common-api", "jei-neoforge-api"]